# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1243, 856)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Ana layout: Sayfayı tamamen ortalamak için
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLayout.setContentsMargins(40, 40, 40, 40)
        self.mainLayout.setSpacing(40)

        # Üst başlık etiketi
        self.lblTop = QtWidgets.QLabel(self.centralwidget)
        font_lbl = QtGui.QFont("Rockwell", 20)
        self.lblTop.setFont(font_lbl)
        self.lblTop.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTop.setObjectName("lblTop")
        self.lblTop.setText("Comparison of Current Encryption Algorithms")
        self.mainLayout.addWidget(self.lblTop)

        # Algoritma butonları için GridLayout
        self.algorithmLayout = QtWidgets.QGridLayout()
        self.algorithmLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.algorithmLayout.setHorizontalSpacing(50)
        self.algorithmLayout.setVerticalSpacing(30)

        self.btnOldEncryption = self.createButton("btnOldEncryption", "Old Encryption Algorithms")
        self.algorithmLayout.addWidget(self.btnOldEncryption, 0, 0)

        self.btnSymmetricEncryption = self.createButton("btnSymmetricEncryption", "Symmetric Encryption Algorithms")
        self.algorithmLayout.addWidget(self.btnSymmetricEncryption, 0, 1)

        self.btnAsymmetricEncryption = self.createButton("btnAsymmetricEncryption", "Asymmetric Encryption Algorithms")
        self.algorithmLayout.addWidget(self.btnAsymmetricEncryption, 0, 2)

        self.btnHashingAlgorithms = self.createButton("btnHashingAlgorithms", "Hashing Algorithms")
        self.algorithmLayout.addWidget(self.btnHashingAlgorithms, 1, 0)

        self.btnHybridAlgorithms = self.createButton("btnHybridAlgorithms", "Hybrid Algorithms")
        self.algorithmLayout.addWidget(self.btnHybridAlgorithms, 1, 1)

        self.btnModernAlgorithms = self.createButton("btnModernAlgorithms", "Modern Encryption Algorithms")
        self.algorithmLayout.addWidget(self.btnModernAlgorithms, 1, 2)

        self.btnQuantumAlgorithms = self.createButton("btnQuantumAlgorithms", "Quantum Encryption Algorithms")
        self.algorithmLayout.addWidget(self.btnQuantumAlgorithms, 2, 1)

        self.mainLayout.addLayout(self.algorithmLayout)

        # Karşılaştırma butonları için HBoxLayout
        self.comparisonLayout = QtWidgets.QHBoxLayout()
        self.comparisonLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.comparisonLayout.setSpacing(50)

        self.btnSymmetrivsAsymmetric = self.createButton("btnSymmetrivsAsymmetric", "Simetrik vs Asimetrik")
        self.comparisonLayout.addWidget(self.btnSymmetrivsAsymmetric)

        self.btnSymmetrivsHybrid = self.createButton("btnSymmetrivsHybrid", "Simetrik vs Hybrid")
        self.comparisonLayout.addWidget(self.btnSymmetrivsHybrid)

        self.btnModernvsOld = self.createButton("btnModernvsOld", "Modern vs Old")
        self.comparisonLayout.addWidget(self.btnModernvsOld)

        self.mainLayout.addLayout(self.comparisonLayout)

        MainWindow.setCentralWidget(self.centralwidget)

    def createButton(self, objectName, text):
        """Buton oluşturma fonksiyonu."""
        button = QtWidgets.QPushButton()
        button.setObjectName(objectName)
        button.setText(text)
        font = QtGui.QFont("Rockwell", 10)
        button.setFont(font)
        button.setFixedHeight(50)
        button.setFixedWidth(300)  # Genişlik artırıldı
        button.setStyleSheet("""
            QPushButton {
                padding: 5px; 
                text-align: center; 
                word-wrap: true; 
                font-size: 10pt;
            }
        """)
        return button

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))