# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OldAlgorithms.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Old_Encryption_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1000)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 0, 670, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        # groupbox for selecting the first algorithm
        self.grpBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.grpBox1.setGeometry(QtCore.QRect(30, 70, 531, 181))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grpBox1.setFont(font)
        self.grpBox1.setStyleSheet("QGroupBox {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.grpBox1.setObjectName("grpBox1")
        
        # radio button for caesar cipher in groupbox1
        self.rdCaesar1 = QtWidgets.QRadioButton(self.grpBox1)
        self.rdCaesar1.setGeometry(QtCore.QRect(30, 50, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdCaesar1.setFont(font)
        self.rdCaesar1.setObjectName("rdCaesar1")
        self.rdCaesar1.setChecked(False)
        
        # radio button for viegerene cipher in groupbox1
        self.rdVigenere1 = QtWidgets.QRadioButton(self.grpBox1)
        self.rdVigenere1.setGeometry(QtCore.QRect(30, 90, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdVigenere1.setFont(font)
        self.rdVigenere1.setObjectName("rdVigenere1")
        self.rdVigenere1.setChecked(False)
        
        # radio button for substitution cipher in groupbox1
        self.rdSubstitution1 = QtWidgets.QRadioButton(self.grpBox1)
        self.rdSubstitution1.setGeometry(QtCore.QRect(30, 130, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdSubstitution1.setFont(font)
        self.rdSubstitution1.setObjectName("rdSubstitution1")
        self.rdSubstitution1.setChecked(False)
        
        # radio button for transposition cipher in groupbox1
        self.rdTransposition1 = QtWidgets.QRadioButton(self.grpBox1)
        self.rdTransposition1.setGeometry(QtCore.QRect(260, 50, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdTransposition1.setFont(font)
        self.rdTransposition1.setObjectName("rdTransposition1")
        self.rdTransposition1.setChecked(False)
        
        # radio button for playfair cipher in groupbox1
        self.rdPlayfair1 = QtWidgets.QRadioButton(self.grpBox1)
        self.rdPlayfair1.setGeometry(QtCore.QRect(260, 90, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdPlayfair1.setFont(font)
        self.rdPlayfair1.setObjectName("rdPlayfair1")
        self.rdPlayfair1.setChecked(False)
        
        # radio button for enigma machine in groupbox1
        self.rdEnigma1 = QtWidgets.QRadioButton(self.grpBox1)
        self.rdEnigma1.setGeometry(QtCore.QRect(260, 130, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdEnigma1.setFont(font)
        self.rdEnigma1.setObjectName("rdEnigma1")
        self.rdEnigma1.setChecked(False)
        
        # groupbox for selecting the second algorithm
        self.grpBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.grpBox2.setGeometry(QtCore.QRect(30, 530, 531, 181))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grpBox2.setFont(font)
        self.grpBox2.setStyleSheet("QGroupBox {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.grpBox2.setObjectName("grpBox2")
        
        # radio button for caesar cipher in groupbox2
        self.rdCaesar2 = QtWidgets.QRadioButton(self.grpBox2)
        self.rdCaesar2.setGeometry(QtCore.QRect(30, 50, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdCaesar2.setFont(font)
        self.rdCaesar2.setObjectName("rdCaesar2")
        self.rdCaesar2.setChecked(False)
        
        # radio button for viegerene cipher in groupbox2
        self.rdVigenere2 = QtWidgets.QRadioButton(self.grpBox2)
        self.rdVigenere2.setGeometry(QtCore.QRect(30, 90, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdVigenere2.setFont(font)
        self.rdVigenere2.setObjectName("rdVigenere2")
        self.rdVigenere2.setChecked(False)
        
        # radio button for substitution cipher in groupbox2
        self.rdSubstitution2 = QtWidgets.QRadioButton(self.grpBox2)
        self.rdSubstitution2.setGeometry(QtCore.QRect(30, 130, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdSubstitution2.setFont(font)
        self.rdSubstitution2.setObjectName("rdSubstitution2")
        self.rdSubstitution2.setChecked(False)
        
        # radio button for transposition cipher in groupbox2
        self.rdTransposition2 = QtWidgets.QRadioButton(self.grpBox2)
        self.rdTransposition2.setGeometry(QtCore.QRect(260, 50, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdTransposition2.setFont(font)
        self.rdTransposition2.setObjectName("rdTransposition2")
        self.rdTransposition2.setChecked(False)
        
        # radio button for playfair cipher in groupbox2
        self.rdPlayfair2 = QtWidgets.QRadioButton(self.grpBox2)
        self.rdPlayfair2.setGeometry(QtCore.QRect(260, 90, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdPlayfair2.setFont(font)
        self.rdPlayfair2.setObjectName("rdPlayfair2")
        self.rdPlayfair2.setChecked(False)
        
        # radio button for enigma machine in groupbox2
        self.rdEnigma2 = QtWidgets.QRadioButton(self.grpBox2)
        self.rdEnigma2.setGeometry(QtCore.QRect(260, 130, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.rdEnigma2.setFont(font)
        self.rdEnigma2.setObjectName("rdEnigma2")
        self.rdEnigma2.setChecked(False)
        
        # groupbox for encrypting and decrypting the input
        self.grpBoxEncrypt = QtWidgets.QGroupBox(self.centralwidget)
        self.grpBoxEncrypt.setGeometry(QtCore.QRect(30, 290, 431, 191))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grpBoxEncrypt.setFont(font)
        self.grpBoxEncrypt.setStyleSheet("QGroupBox {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.grpBoxEncrypt.setObjectName("grpBoxEncrypt")
        
        # text box for input to encrypt
        self.txtBoxEncrypt = QtWidgets.QTextEdit(self.grpBoxEncrypt)
        self.txtBoxEncrypt.setGeometry(QtCore.QRect(30, 30, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.txtBoxEncrypt.setFont(font)
        self.txtBoxEncrypt.setObjectName("txtBoxEncrypt")
        
        # button for encrypting the input
        self.btnEncrypt = QtWidgets.QPushButton(self.grpBoxEncrypt)
        self.btnEncrypt.setGeometry(QtCore.QRect(100, 90, 93, 28))
        self.btnEncrypt.setObjectName("btnEncrypt")
        
        # button for decrypting the input
        self.btnDecrypt = QtWidgets.QPushButton(self.grpBoxEncrypt)
        self.btnDecrypt.setGeometry(QtCore.QRect(220, 90, 93, 28))
        self.btnDecrypt.setObjectName("btnDecrypt")
        
        # text box for decrypted input
        self.txtBoxDecrypt = QtWidgets.QTextEdit(self.grpBoxEncrypt)
        self.txtBoxDecrypt.setGeometry(QtCore.QRect(30, 130, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.txtBoxDecrypt.setFont(font)
        self.txtBoxDecrypt.setObjectName("txtBoxDecrypt")
        
        # text box for key 1
        self.txtBoxKey1 = QtWidgets.QTextEdit(self.grpBoxEncrypt)
        self.txtBoxKey1.setGeometry(QtCore.QRect(320, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.txtBoxKey1.setFont(font)
        self.txtBoxKey1.setObjectName("txtBoxKey1")
        
        # text box for key 2
        self.txtBoxKey2 = QtWidgets.QTextEdit(self.grpBoxEncrypt)
        self.txtBoxKey2.setGeometry(QtCore.QRect(320, 130, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.txtBoxKey2.setFont(font)
        self.txtBoxKey2.setObjectName("txtBoxKey2")
        
        # graph for performance
        self.graphPerformance = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphPerformance.setGeometry(QtCore.QRect(650, 100, 401, 281))  # Genişlik ve yükseklik büyütüldü
        self.graphPerformance.setObjectName("graphPerformance")

        # graph for security
        self.graphSecurity = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphSecurity.setGeometry(QtCore.QRect(1100, 100, 401, 281))  # Genişlik ve yükseklik büyütüldü
        self.graphSecurity.setObjectName("graphSecurity")

        # graph for memory usage
        self.graphMemoryUsage = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphMemoryUsage.setGeometry(QtCore.QRect(650, 450, 401, 281))  # Genişlik ve yükseklik büyütüldü
        self.graphMemoryUsage.setObjectName("graphMemoryUsage")

        

        # button for comparing the algorithms
        self.btnCompare = QtWidgets.QPushButton(self.centralwidget)
        self.btnCompare.setGeometry(QtCore.QRect(680, 800, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnCompare.setFont(font)
        self.btnCompare.setObjectName("btnCompare")


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(760, 70, 201, 31))  # Konum ve boyut büyütüldü
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(760, 420, 201, 31))  # Konum ve boyut büyütüldü
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1200, 70, 291, 31))  # Konum ve boyut büyütüldü
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 23))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Comparison of Old Encryption Algorithms"))
        self.grpBox1.setTitle(_translate("MainWindow", "Select Algorithm 1 to compare(for input, choose your function here)"))
        self.rdCaesar1.setText(_translate("MainWindow", "Caesar Cipher"))
        self.rdVigenere1.setText(_translate("MainWindow", "Vigenere Cipher"))
        self.rdSubstitution1.setText(_translate("MainWindow", "Substitution Cipher"))
        self.rdTransposition1.setText(_translate("MainWindow", "Transposition Cipher"))
        self.rdPlayfair1.setText(_translate("MainWindow", "Playfair Cipher"))
        self.rdEnigma1.setText(_translate("MainWindow", "Enigma Machine"))
        self.grpBox2.setTitle(_translate("MainWindow", "Select Algorithm 2 to compare"))
        self.rdCaesar2.setText(_translate("MainWindow", "Caesar Cipher"))
        self.rdVigenere2.setText(_translate("MainWindow", "Vigenere Cipher"))
        self.rdSubstitution2.setText(_translate("MainWindow", "Substitution Cipher"))
        self.rdTransposition2.setText(_translate("MainWindow", "Transposition Cipher"))
        self.rdPlayfair2.setText(_translate("MainWindow", "Playfair Cipher"))
        self.rdEnigma2.setText(_translate("MainWindow", "Enigma Machine"))
        self.grpBoxEncrypt.setTitle(_translate("MainWindow", "Input to encrypt"))
        self.btnEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btnCompare.setText(_translate("MainWindow", "Compare them according to some metrics"))
        self.label_2.setText(_translate("MainWindow", "Performance"))
        self.label_3.setText(_translate("MainWindow", "Memory Usage"))
        self.label_4.setText(_translate("MainWindow", "Frequency Analysis"))
     
    def reset_form(self):
        self.rdCaesar1.setChecked(False)
        self.rdVigenere1.setChecked(False)
        self.rdSubstitution1.setChecked(False)
        self.rdTransposition1.setChecked(False)
        self.rdPlayfair1.setChecked(False)
        self.rdEnigma1.setChecked(False)
        
        self.rdCaesar2.setChecked(False)
        self.rdVigenere2.setChecked(False)
        self.rdSubstitution2.setChecked(False)
        self.rdTransposition2.setChecked(False)
        self.rdPlayfair2.setChecked(False)
        self.rdEnigma2.setChecked(False)
        
        self.txtBoxEncrypt.setText("")
        self.txtBoxDecrypt.setText("")
        self.txtBoxKey1.setText("")
        self.txtBoxKey2.setText("")
        
        self.graphPerformance.clear()
        self.graphSecurity.clear()
        self.graphMemoryUsage.clear()
        
    


